//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C01_DesignProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C01_DesignProject()
        {
            this.C24_Issue = new HashSet<C24_Issue>();
            this.C15_TimeSheet = new HashSet<C15_TimeSheet>();
        }
    
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectOtherName { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public string ProjectStatus { get; set; }
        public string ProjectState { get; set; }
        public Nullable<int> ProjectLocation { get; set; }
        public Nullable<int> Project_Manager { get; set; }
        public string BIM_staff { get; set; }
        public string BIM_MEP_staff { get; set; }
        public string Modeling_ARC_main { get; set; }
        public string Modeling_ARC_sub { get; set; }
        public string Modeling_STR { get; set; }
        public string Modeling_MEP { get; set; }
        public string CTC_group { get; set; }
        public string Site { get; set; }
        public string Outsource { get; set; }
        public string BIM_target { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> Finish { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Image { get; set; }
        public string Tracking_detail { get; set; }
        public string Year { get; set; }
        public string ARC_status { get; set; }
        public string STR_status { get; set; }
        public string MEP_status { get; set; }
        public string Civil_Status { get; set; }
        public string Problems { get; set; }
        public string Solution { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C24_Issue> C24_Issue { get; set; }
        public virtual C04_DMC_PMlist C04_DMC_PMlist { get; set; }
        public virtual C06a_ProjectType C06a_ProjectType { get; set; }
        public virtual C11_OutsourceList C11_OutsourceList { get; set; }
        public virtual C12_SiteList C12_SiteList { get; set; }
        public virtual C13_Location C13_Location { get; set; }
        public virtual C06_ProjectType C06_ProjectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C15_TimeSheet> C15_TimeSheet { get; set; }
    }
}
