//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C05_BIMtarget
    {
        public string ID { get; set; }
        public string TargetName { get; set; }
        public string Project_Type { get; set; }
        public string Descipline_Group { get; set; }
        public Nullable<bool> Tender { get; set; }
        public Nullable<bool> Design { get; set; }
        public Nullable<bool> Site { get; set; }
        public Nullable<bool> Architech { get; set; }
        public Nullable<bool> Structure { get; set; }
        public Nullable<bool> MEP { get; set; }
        public Nullable<bool> Civil { get; set; }
        public Nullable<bool> Facade { get; set; }
    }
}
