//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C24_Issue
    {
        public int ID { get; set; }
        public string ProjectID { get; set; }
        public int MemberID { get; set; }
        public string IssueCode { get; set; }
        public string Descipline { get; set; }
        public string IssueStatus { get; set; }
        public Nullable<int> NoOfRepeat { get; set; }
        public string Source { get; set; }
        public string Level { get; set; }
        public string Tower { get; set; }
        public string Grid { get; set; }
        public string IssueDescription { get; set; }
        public string Solution { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual C01_DesignProject C01_DesignProject { get; set; }
        public virtual C02_BIMstaff C02_BIMstaff { get; set; }
    }
}
